/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Employee;
import model.EmployeeDirectory;


/**
 *
 * @author evelynzu
 */
public class ViewJPanel extends javax.swing.JPanel {

   
    EmployeeDirectory directory;

    public ViewJPanel(EmployeeDirectory directory) {
        initComponents();

        this.directory = directory;

        populateTable();
        sort(model);

        //set edit element invisible for clean and tidy panel
        btnUpdateImage.setVisible(false);
        btnEdit.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel11.setVisible(false);
        txtName.setVisible(false);
        txtAge.setVisible(false);
        txtGender.setVisible(false);
        txtCellPhone.setVisible(false);
        txtEmail.setVisible(false);
        txtId.setVisible(false);
        txtLevel.setVisible(false);
        txtPosition.setVisible(false);
        txtStartDate.setVisible(false);
        txtTeamInfo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCellPhone = new javax.swing.JTextField();
        icImage = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbSearch = new javax.swing.JComboBox<>();
        btnUpdateImage = new javax.swing.JButton();

        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(150, 25));
        setSize(new java.awt.Dimension(150, 25));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Level", "Team", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel5.setText("gender:");

        jLabel6.setText("start date:");

        jLabel11.setText("email:");

        jLabel7.setText("level:");

        jLabel2.setText("id:");

        jLabel8.setText("team info:");

        jLabel3.setText("name:");

        jLabel4.setText("age:");

        jLabel9.setText("position:");

        txtId.setMaximumSize(null);
        txtId.setMinimumSize(new java.awt.Dimension(150, 25));
        txtId.setPreferredSize(new java.awt.Dimension(150, 25));
        txtId.setSize(new java.awt.Dimension(150, 25));

        txtName.setMaximumSize(null);
        txtName.setMinimumSize(new java.awt.Dimension(150, 25));
        txtName.setPreferredSize(new java.awt.Dimension(150, 25));
        txtName.setSize(new java.awt.Dimension(150, 25));

        txtAge.setMaximumSize(null);
        txtAge.setMinimumSize(new java.awt.Dimension(150, 25));
        txtAge.setPreferredSize(new java.awt.Dimension(150, 25));
        txtAge.setSize(new java.awt.Dimension(150, 25));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtGender.setMaximumSize(null);
        txtGender.setMinimumSize(new java.awt.Dimension(150, 25));
        txtGender.setPreferredSize(new java.awt.Dimension(150, 25));
        txtGender.setSize(new java.awt.Dimension(150, 25));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        txtStartDate.setMaximumSize(null);
        txtStartDate.setMinimumSize(new java.awt.Dimension(150, 25));
        txtStartDate.setPreferredSize(new java.awt.Dimension(150, 25));
        txtStartDate.setSize(new java.awt.Dimension(150, 25));
        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        txtLevel.setMaximumSize(null);
        txtLevel.setMinimumSize(new java.awt.Dimension(150, 25));
        txtLevel.setPreferredSize(new java.awt.Dimension(150, 25));
        txtLevel.setSize(new java.awt.Dimension(150, 25));
        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });

        txtPosition.setMaximumSize(null);
        txtPosition.setMinimumSize(new java.awt.Dimension(150, 25));
        txtPosition.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPosition.setSize(new java.awt.Dimension(150, 25));
        txtPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionActionPerformed(evt);
            }
        });

        txtTeamInfo.setMaximumSize(null);
        txtTeamInfo.setMinimumSize(new java.awt.Dimension(150, 25));
        txtTeamInfo.setPreferredSize(new java.awt.Dimension(150, 25));
        txtTeamInfo.setSize(new java.awt.Dimension(150, 25));
        txtTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamInfoActionPerformed(evt);
            }
        });

        txtEmail.setMaximumSize(null);
        txtEmail.setMinimumSize(new java.awt.Dimension(150, 25));
        txtEmail.setPreferredSize(new java.awt.Dimension(150, 25));
        txtEmail.setSize(new java.awt.Dimension(150, 25));

        txtCellPhone.setMaximumSize(null);
        txtCellPhone.setMinimumSize(new java.awt.Dimension(150, 25));
        txtCellPhone.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCellPhone.setSize(new java.awt.Dimension(150, 25));
        txtCellPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellPhoneActionPerformed(evt);
            }
        });

        icImage.setSize(new java.awt.Dimension(200, 200));

        btnEdit.setText("Edit and Save");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("phone:");

        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all Field", "employee ID", "name", "team info", "position" }));
        cbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSearchActionPerformed(evt);
            }
        });

        btnUpdateImage.setText("update photo");
        btnUpdateImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(99, 99, 99)
                .addComponent(btnView)
                .addGap(86, 86, 86)
                .addComponent(btnDelete)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(icImage, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCellPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnEdit))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnUpdateImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnView)
                        .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addComponent(btnDelete))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(icImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateImage)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(31, 31, 31))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        int selectedRowIndex = tblEmployees.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();

  Employee selectedEmployee = (Employee) model.getValueAt(selectedRowIndex, 0);
        directory.deleteEmployee(selectedEmployee);

        JOptionPane.showMessageDialog(this, "Employee deleted");

        //re-populate employee table
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // set element visible
        btnUpdateImage.setVisible(true);
        btnEdit.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        jLabel11.setVisible(true);
        txtName.setVisible(true);
        txtAge.setVisible(true);
        txtGender.setVisible(true);
        txtCellPhone.setVisible(true);
        txtEmail.setVisible(true);
        txtId.setVisible(true);
        txtLevel.setVisible(true);
        txtPosition.setVisible(true);
        txtStartDate.setVisible(true);
        txtTeamInfo.setVisible(true);
        

        //display selected employee information
        int selectedRowIndex = tblEmployees.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        Employee selectedEmployee = (Employee) model.getValueAt(selectedRowIndex, 0);

        txtId.setText(selectedEmployee.getId());
        txtName.setText(selectedEmployee.getName());
        txtAge.setText(String.valueOf(selectedEmployee.getAge()));
        txtGender.setText(selectedEmployee.getGender());
        txtStartDate.setText(selectedEmployee.getStartDate());
        txtLevel.setText(String.valueOf(selectedEmployee.getLevel()));
        txtPosition.setText(selectedEmployee.getPosition());
        txtTeamInfo.setText(selectedEmployee.getTeam());
        txtEmail.setText(selectedEmployee.getEmail());
        txtCellPhone.setText(selectedEmployee.getPhone());

        //display employee poto
        ImageIcon imageIcon = new ImageIcon(
                new ImageIcon(selectedEmployee.getPhoto()).getImage()
                        .getScaledInstance(200, 200, Image.SCALE_DEFAULT));

//        ImageIcon imageIcon1 = new ImageIcon(selectedEmployee.getPhone()).getImage();
        icImage.setIcon(imageIcon);

// imageIcon = resize(imageIcon, 150, 200);

    }//GEN-LAST:event_btnViewActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void txtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionActionPerformed

    private void txtTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamInfoActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       
        //get employee selected
        int selectedRowIndex = tblEmployees.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        Employee employee = (Employee) model.getValueAt(selectedRowIndex, 0);
        String name = txtName.getText();
        String employeeID = txtId.getText();

        int age;
        try {
            age = Integer.parseInt(txtAge.getText());
        } catch (Exception e) {
            age = 0;
        }

        String gender = txtGender.getText();
        String startDate = txtStartDate.getText();
        int level;
        try {
            level = Integer.parseInt(txtLevel.getText());
        } catch (Exception e) {
            level = 0;
        }

        String teamInfo = txtTeamInfo.getText();
        String positionTitle = txtPosition.getText();
        String phoneNumber = txtCellPhone.getText();
        String email = txtEmail.getText();

        String nameNoSpace = name.replace(" ", "");
        String idNoe = employeeID.substring(1, employeeID.length());
        String photo = "src/resource/images/" + nameNoSpace + idNoe + ".png";

        //set new information to employee
        employee.setName(name);
        employee.setId(employeeID);
        employee.setAge(age);
        employee.setGender(gender);
        employee.setStartDate(startDate);
        employee.setLevel(level);
        employee.setTeam(teamInfo);
        employee.setPosition(positionTitle);
        employee.setPhone(phoneNumber);
        employee.setEmail(email);
        employee.setPhoto(photo);

        directory.editEmployee(employee);

        //update photo
        if (bi == null) {
        } else {
            try {
                // retrieve image
                //                BufferedImage bi = getMyImage();
                File outputfile = new File("src/resource/images/" + nameNoSpace + idNoe + ".png");

                ImageIO.write((RenderedImage) bi, "png", outputfile);
            } catch (Exception e) {
            }
        }

        JOptionPane.showMessageDialog(this, "Save successfully");

        populateTable();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //get search text
        String searchText = SearchField.getText();

        int searchIndex = cbSearch.getSelectedIndex();
        int col = 5;
        String text = "(?i)" + searchText;
        
        //search with specific field or whole table
        if (text.trim().length() == 0) {
            myTableRowSorter.setRowFilter(null);
        }
        if (0 == searchIndex) {
            myTableRowSorter.setRowFilter(RowFilter.regexFilter(text));
        } else {
            
            if (1 == searchIndex) {
                //employee id
                col = 0;
            } else if (2 == searchIndex) {
                //employee name
                col = 1;
            } else if (3 == searchIndex) {
                //team information
                col = 5;
            } else if (4 == searchIndex) {
                //position
                col = 6;
            }
            myTableRowSorter.setRowFilter(RowFilter.regexFilter(text, col));
        }

        SearchField.setText("");


    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSearchActionPerformed
        // TODO add your handling code here:
//        jComboBox1.addItem(2);
    }//GEN-LAST:event_cbSearchActionPerformed

    private void btnUpdateImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateImageActionPerformed
        //upload image
        
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Choose Your File");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
         // below code selects the file 
        int returnval = filechooser.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();

            try {
                // display the image in imagelabel
                bi = ImageIO.read(file);
                bi = resize(bi, 200, 200);

                icImage.setIcon(new ImageIcon(bi));
            } catch (IOException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnUpdateImageActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtCellPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCellPhoneActionPerformed

    DefaultTableModel model;
    TableRowSorter myTableRowSorter;
    BufferedImage bi;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchField;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateImage;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JLabel icImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCellPhone;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        tblEmployees.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblEmployees.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblEmployees.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblEmployees.getColumnModel().getColumn(3).setPreferredWidth(40);
        tblEmployees.getColumnModel().getColumn(4).setPreferredWidth(20);
        tblEmployees.getColumnModel().getColumn(5).setPreferredWidth(80);

        model = (DefaultTableModel) tblEmployees.getModel();
        model.setRowCount(0);

        for (Employee employee : directory.getDirectory()) {
            Object[] row = new Object[7];
            row[0] = employee;
            row[1] = employee.getName();
            row[2] = employee.getAge();
            row[3] = employee.getGender();
            row[4] = employee.getLevel();
            row[5] = employee.getTeam();
            row[6] = employee.getPosition();

            model.addRow(row);
        }

    }

    public void sort(DefaultTableModel model) {
        myTableRowSorter = new TableRowSorter(model);
        tblEmployees.setRowSorter(myTableRowSorter);
    }

    public static BufferedImage resize(BufferedImage img, int newW, int newH) {
        BufferedImage dimg = null;
        try {
            Image tmp = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
            dimg = new BufferedImage(newW, newH, BufferedImage.TYPE_INT_ARGB);

            Graphics2D g2d = dimg.createGraphics();
            g2d.setClip(new RoundRectangle2D.Float(0, 0, newW, newH, 5, 5));
            g2d.drawImage(tmp, 0, 0, null);

            g2d.dispose();
        } catch (Exception e) {
        }

        return dimg;
    }
}
